import "dotenv/config";
import express from "express";
import { webhookCallback } from "grammy";
import { askAI, askAIStream, checkAI, createBot } from "./bot.js";
import { addGuest, addTask, allWeddings, budgetItems, cardData, cardRsvp, checkStorage, cycleTask, dueReminders, getProfile, guests, markReminderSent, progress, removeGuest, saveChat, setBudgetItem, setGuestRsvp, setTaskDone, storageMode, tasksFor, toggleCompareVendor, toggleSavedVendor, updateProfile, vendorState, vendors } from "./store.js";
import { telegramUser } from "./telegram-auth.js";

const token=process.env.TELEGRAM_BOT_TOKEN;
const publicUrl=(process.env.PUBLIC_URL?.trim()||process.env.RENDER_EXTERNAL_URL?.trim()||"http://localhost:3000").replace(/\/$/,"");
const port=Number(process.env.PORT??3000); if(!token) throw new Error("TELEGRAM_BOT_TOKEN is required.");
const botToken:string=token;
const app=express(),bot=createBot(botToken,publicUrl),useWebhook=publicUrl.startsWith("https://");
app.use(express.json({limit:"100kb"})); app.use(express.static("public"));
app.get("/card/:weddingId",(_req,res)=>res.sendFile("card/index.html",{root:process.cwd()+"/public"}));
app.get("/health",async(req,res)=>{const db=await checkStorage();const body:any={ok:true,storage:storageMode(),db};if(req.query.ai)body.ai=await checkAI();res.json(body);});

function api(handler:(req:any,res:any,userId:number)=>Promise<any>){return async(req:any,res:any)=>{try{const userId=telegramUser(req,botToken);await handler(req,res,userId);}catch(error:any){res.status(error?.message?.includes("Telegram")?401:500).json({error:error?.message??"Unexpected error"});}};}
app.get("/api/dashboard",api(async(_req,res,userId)=>{const [profile,tasks,value,vendorList,budget]=await Promise.all([getProfile(userId),tasksFor(userId),progress(userId),vendorState(userId),budgetItems(userId)]);res.json({profile,tasks,progress:value,vendors:vendorList,budget});}));
app.get("/api/tasks",api(async(_req,res,userId)=>res.json(await tasksFor(userId))));
app.post("/api/tasks/:taskId/cycle",api(async(req,res,userId)=>{const task=await cycleTask(userId,req.params.taskId);if(!task)return res.status(404).json({error:"Task not found"});res.json(task);}));
app.post("/api/tasks/:taskId/toggle",api(async(req,res,userId)=>{const task=await setTaskDone(userId,req.params.taskId,Boolean(req.body?.done));if(!task)return res.status(404).json({error:"Task not found"});res.json(task);}));
app.post("/api/tasks",api(async(req,res,userId)=>{const title=String(req.body?.title??"").trim();if(!title)return res.status(400).json({error:"Title required"});res.json(await addTask(userId,title,String(req.body?.category??"Planning"))); }));
app.get("/api/guests",api(async(_req,res,userId)=>res.json(await guests(userId))));
app.post("/api/guests",api(async(req,res,userId)=>{const name=String(req.body?.name??"").trim();if(!name)return res.status(400).json({error:"Name required"});res.json(await addGuest(userId,name,Number(req.body?.pax)||1));}));
app.patch("/api/guests/:id",api(async(req,res,userId)=>{const rsvp=String(req.body?.rsvp);if(!["pending","yes","no"].includes(rsvp))return res.status(400).json({error:"Invalid RSVP"});const g=await setGuestRsvp(userId,req.params.id,rsvp as any);if(!g)return res.status(404).json({error:"Guest not found"});res.json(g);}));
app.delete("/api/guests/:id",api(async(req,res,userId)=>{await removeGuest(userId,req.params.id);res.json({ok:true});}));
app.get("/api/card/:weddingId",async(req,res)=>{try{const card=await cardData(req.params.weddingId);if(!card)return res.status(404).json({error:"Invitation not found"});res.json(card);}catch(error:any){res.status(500).json({error:error?.message??"Error"});}});
app.post("/api/card/:weddingId/rsvp",async(req,res)=>{try{const name=String(req.body?.name??"").trim();if(!name)return res.status(400).json({error:"Name required"});const rsvp=String(req.body?.rsvp);if(!["yes","no"].includes(rsvp))return res.status(400).json({error:"Invalid RSVP"});const ok=await cardRsvp(req.params.weddingId,name,Number(req.body?.pax)||1,rsvp as any);if(!ok)return res.status(404).json({error:"Invitation not found"});res.json({ok:true});}catch(error:any){res.status(500).json({error:error?.message??"Error"});}});
app.get("/api/budget",api(async(_req,res,userId)=>res.json(await budgetItems(userId))));
app.patch("/api/budget/:category",api(async(req,res,userId)=>{const patch:any={};if(req.body?.allocated!=null)patch.allocated=Math.max(0,Number(req.body.allocated)||0);if(req.body?.spent!=null)patch.spent=Math.max(0,Number(req.body.spent)||0);res.json(await setBudgetItem(userId,req.params.category,patch));}));
app.patch("/api/profile",api(async(req,res,userId)=>{const allowed=["partnerName","weddingDate","location","budget","guestCount","eventType","remindersEnabled","venue","ceremonyTime","hosts","cardMessage"];const patch=Object.fromEntries(Object.entries(req.body??{}).filter(([key])=>allowed.includes(key)));res.json(await updateProfile(userId,patch));}));
app.get("/api/vendors",api(async(req,res)=>res.json(await vendors(typeof req.query.category==="string"?req.query.category:undefined))));
app.post("/api/vendors/:vendorId/save",api(async(req,res,userId)=>res.json({saved:await toggleSavedVendor(userId,req.params.vendorId)})));
app.post("/api/vendors/:vendorId/compare",api(async(req,res,userId)=>res.json({compareSelected:await toggleCompareVendor(userId,req.params.vendorId)})));
app.post("/api/chat",api(async(req,res,userId)=>{const question=String(req.body?.message??"").trim().slice(0,2000);if(!question)return res.status(400).json({error:"Message required"});await saveChat(userId,"user",question);const answer=await askAI(userId,question);await saveChat(userId,"assistant",answer);res.json({answer});}));
app.post("/api/chat/stream",async(req,res)=>{let userId:number;try{userId=telegramUser(req,botToken);}catch(error:any){return res.status(401).json({error:error?.message??"Unauthorized"});}const question=String(req.body?.message??"").trim().slice(0,2000);if(!question)return res.status(400).json({error:"Message required"});res.setHeader("Content-Type","text/event-stream");res.setHeader("Cache-Control","no-cache, no-transform");res.setHeader("Connection","keep-alive");res.setHeader("X-Accel-Buffering","no");(res as any).flushHeaders?.();await saveChat(userId,"user",question);let full="";try{for await(const token of askAIStream(userId,question)){full+=token;res.write(`data: ${JSON.stringify({token})}\n\n`);}if(full.trim()){await saveChat(userId,"assistant",full);}else{res.write(`data: ${JSON.stringify({token:"Restu couldn't generate an answer right now. Please try again in a moment."})}\n\n`);}res.write(`data: ${JSON.stringify({done:true})}\n\n`);}catch(error:any){console.error("AI stream error",error);res.write(`data: ${JSON.stringify({error:"Restu AI is temporarily unavailable. Please try again shortly."})}\n\n`);}res.end();});

app.post("/internal/reminders",async(req,res)=>{if(!process.env.CRON_SECRET||req.header("authorization")!==`Bearer ${process.env.CRON_SECRET}`)return res.status(401).json({error:"Unauthorized"});const items=await dueReminders();let sent=0;for(const item of items){try{await bot.api.sendMessage(item.telegramId,`Wedding task due\n\n${item.task.title}\n${item.task.dueDate??"Due now"}`,{reply_markup:{inline_keyboard:[[{text:"Open checklist",callback_data:"checklist"}]]}});await markReminderSent(item.task.id);sent++;}catch(error){console.error("Reminder failed",error);}}res.json({ok:true,sent});});
app.post("/internal/digest",async(req,res)=>{if(!process.env.CRON_SECRET||req.header("authorization")!==`Bearer ${process.env.CRON_SECRET}`)return res.status(401).json({error:"Unauthorized"});const weddings=await allWeddings();const weekly=new Date().getDay()===1;const milestones=[100,60,30,14,7,3,1];const openApp={reply_markup:{inline_keyboard:[[{text:"Open Restu.ai",web_app:{url:`${publicUrl}/app`}}]]}};let sent=0;for(const w of weddings){try{const days=w.weddingDate?Math.ceil((new Date(`${w.weddingDate}T00:00:00`).getTime()-Date.now())/86400000):undefined;const prog=await progress(w.telegramId);const open=prog.total-prog.completed;let msg:string|null=null;if(days!==undefined&&days>=0&&milestones.includes(days)){msg=`${days} ${days===1?"day":"days"} to go until your wedding.\n\n${prog.completed}/${prog.total} tasks done (${prog.percent}%). ${open>0?`${open} still to go — you've got this.`:"Everything's ready. Congratulations!"}`;}else if(weekly){msg=`Your weekly wedding update${days!==undefined&&days>=0?` — ${days} days to go`:""}:\n\n${prog.completed}/${prog.total} tasks complete (${prog.percent}%).${open>0?`\n${open} tasks still open — tap below to keep planning.`:"\nAll tasks done!"}`;}if(msg){await bot.api.sendMessage(w.telegramId,msg,openApp);sent++;}}catch(error){console.error("Digest failed",error);}}res.json({ok:true,sent});});
if(useWebhook) app.use("/telegram/webhook",(req,res,next)=>{const secret=process.env.WEBHOOK_SECRET;if(secret&&req.header("x-telegram-bot-api-secret-token")!==secret)return res.sendStatus(401);next();},webhookCallback(bot,"express"));
app.listen(port,async()=>{console.log(`Restu bot listening on port ${port}`);console.log(`Storage: ${storageMode()}`);if(process.env.DISABLE_BOT_START==="true"){console.log("Bot transport disabled for UI testing");return;}console.log(`Bot transport: ${useWebhook?"webhook":"long polling"}`);try{await bot.api.setMyCommands([{command:"start",description:"Open Restu.ai"},{command:"menu",description:"Show the main menu"},{command:"checklist",description:"View your wedding checklist"},{command:"addtask",description:"Add a task, e.g. /addtask Book venue"},{command:"invite",description:"Invite your partner or family"},{command:"help",description:"How to use Restu.ai"}]);console.log("Bot commands configured");}catch(error){console.error("setMyCommands failed",error);}
try{await bot.api.setMyShortDescription("Your AI wedding planner — checklist, budget, vendors and countdown, all in one place.");await bot.api.setMyDescription("Restu.ai is your personal wedding planning assistant for Malaysian weddings.\n\nPlan your checklist, track your budget, discover and compare vendors, watch your countdown, and ask Restu anything — anytime.\n\nTap Start to open your wedding dashboard.");console.log("Bot description configured");}catch(error){console.error("setMyDescription failed",error);}if(publicUrl.startsWith("https://")){try{await bot.api.setChatMenuButton({menu_button:{type:"web_app",text:"Dashboard",web_app:{url:`${publicUrl}/app`}}});console.log("Mini App menu button configured");}catch(error){console.error("Menu button setup failed",error);}}if(useWebhook){await bot.api.setWebhook(`${publicUrl}/telegram/webhook`,{secret_token:process.env.WEBHOOK_SECRET});console.log("Telegram webhook configured");}else{await bot.api.deleteWebhook();bot.start({drop_pending_updates:true});}});
